
title:              DevOps over Ice
email:              leacoighear@gmail.com
description:        >- 
  A storied collection of tips, tricks and traps that I've come across and narrowly avoided
  in my journy into the world of DevOps. As with DevOps, its partly technical and partly cultural, 
  and a whole lot of cringeable.
author:             Tom Ryan
source:             "./blog"
baseurl:            ""
url:                "https://leacoighear.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
twitter_username:   tomcr94
github_username:    tomcr94
linkedin_username:  thomas-ryan-0a076a139

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
