#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: Vlog Empire # REQUIRED - Enter your app name
  ios_id: # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: me.leacoighear.vlogempire # Optional - Enter Android app id like: com.example.app

  icon: images/Icon.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  screenshot: # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

#
# Marketing
#
marketing_header: Create your own Vlogging Empire # Optional
marketing_desc: Take the helm of your very own vlogging channel in this casual clicker style game.

EARN
&#8226;&#8195;Start off with a simple vlogging channel to earn your fortune
&#8226;&#8195;Invest in aspects of your channel to earn more; Camera, Editing, Promotion etc.
&#8226;&#8195;Boost your income for a short time by taking a chance; Your earnings could double or quadruple

EXPAND
&#8226;&#8195;Invest in new Channels with different topics; Food, Gaming, Travel etc.
&#8226;&#8195;Name each Channel whatever you want to reflect your uniqueness
&#8226;&#8195;Watch your income soar, even as you're not in game

EMPLOY
&#8226;&#8195;Boost your profits by employing in game characters
  &#8226;The Ant, an average worker who will boost your profits, but only from 9 to 5
  &#8226;The Zombie, a slow worker who will work day and night to boost your profits marginally
  &#8226;The Director, these workers take charge and increase your boost from Ant workers
&#8226;&#8195;Find unique characters who will bring a new perk to your Empire
  &#8226;Esther Bunny, a little old lady who randomly leaves presents around the office
  &#8226;D. Drump, a narcissist with a penchant for social media
  &#8226;H. Klintun, adverse reaction to emails, looking for a new career
#
# Homebar Links
#
# Includes an icon for each homebar item
#
homebar-links:
  home: /
  mainProjects: projects
  otherProjects: otherProjects
  about: about
  
#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github: TomCR94
  facebook:
  twitter: leacoighear
  pinterest:
  instagram:
  email: leacoighear@gmail.com
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
#background_image: /images/backgrounds/58-usersthink-stock-image-web.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: LeacOighear # Optional - Enter your site title
description: # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
